# =============================================
# = Google Recaptcha configurations
# = https://www.google.com/recaptcha/admin#list
# =============================================
google:
  recaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    key: 6LdjU4oUAAAAAGzHKiwNL82kYbDFCWOpip5q5-CL
    secret: 6LdjU4oUAAAAAO1uhNimkb9OgnieVHTqLd9a5aq7

# =============================================
# = Logging configurations
# =============================================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO